apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mezp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-mezp@sha256:d90b6a6933c633a46e374dddf0a5c3cd6f1df6336af9657633acbe86c70a2cfe
        name: my-nodejs
        resources: {}
status: {}
